pub mod api;
pub mod archive;
pub mod config;
pub mod db;
pub mod export;
pub mod file_content;
pub mod frontend;
pub mod graph;
pub mod image_description;
pub mod image_ocr;
pub mod image_parse;
pub mod log4rs;
pub mod oidc;
pub mod pdf_content;
pub mod pdf_highlight;
pub mod processor;
pub mod search;
pub mod slice_content;

pub mod auth_user;
pub mod kb_acl;
pub use auth_user::{AuthUser, auth};
